<?xml version="1.0" encoding="utf-8"?>
<modules duration="0.43270 ms">
    <module name="cDataLib", failures="18", skipped="1", tests="42", timestamp="2020-04-18 00:45:37">
        <describe name="cSpec functions">
            <it name="succeeds `assert_that`", status="passing" />
            <it name="fails `assert_that`", status="failing">
                <failure>
                    <position line="simple.spec.c:15:" />
                    <error message="|> `1 isnot 1` should be true" />
                </failure>
            <it/>
            <it name="succeeds `nassert_that`", status="passing" />
            <it name="fails `nassert_that`", status="failing">
                <failure>
                    <position line="simple.spec.c:22:" />
                    <error message="|> `2 is 2` should be false" />
                </failure>
            <it/>
            <it name="succeeds `assert_that_int`", status="passing" />
            <it name="fails `assert_that_int`", status="failing">
                <failure>
                    <position line="simple.spec.c:29:" />
                    <error message="|> `3` expected but got `2" />
                </failure>
            <it/>
            <it name="succeeds `nassert_that_int`", status="passing" />
            <it name="fails `nassert_that_int`", status="failing">
                <failure>
                    <position line="simple.spec.c:36:" />
                    <error message="|> `4` expected but got `4" />
                </failure>
            <it/>
            <it name="succeeds `assert_that_double`", status="failing">
                <failure>
                    <position line="simple.spec.c:40:" />
                    <error message="|> `3.2` expected but got `3.2" />
                </failure>
            <it/>
            <it name="fails `assert_that_double`", status="passing" />
            <xit name="SKIP THAT TEST", status="skipped" />
            <it name="succeeds `nassert_that_double`", status="failing">
                <failure>
                    <position line="simple.spec.c:51:" />
                    <error message="|> `7.7` expected but got `6.6" />
                </failure>
            <it/>
            <it name="fails `nassert_that_double`", status="passing" />
            <it name="succeeds `assert_that_string`", status="passing" />
            <it name="fails `assert_that_string`", status="failing">
                <failure>
                    <position line="simple.spec.c:61:" />
                    <error message="|> `nottestme` expected but got `testme" />
                </failure>
            <it/>
            <it name="succeeds `nassert_that_string`", status="passing" />
            <it name="fails `nassert_that_string`", status="failing">
                <failure>
                    <position line="simple.spec.c:68:" />
                    <error message="|> `ok str` expected but got `ok str" />
                </failure>
            <it/>
        </describe>
    </module>
    <module name="second", failures="18", skipped="1", tests="42", timestamp="2020-04-18 00:45:37">
        <describe name="DESC 1">
            <it name="before on desc 1", status="passing" />
            <it name="does on 1", status="passing" />
        </describe>
        <describe name="DESC 2">
            <it name="does on 2", status="passing" />
        </describe>
        <describe name="DESC 3">
            <it name="does on 3", status="passing" />
        </describe>
        <describe name="Array Assertions">
            <it name="succeeds `assert_that_int_array`", status="passing" />
            <it name="fails `assert_that_int_array`", status="failing">
                <failure>
                    <position line="simple.spec.c:109:" />
                    <error message="|> `[7, 7, 7, 7, 7]` expected but got `[1, 2, 3, 4, 5]" />
                </failure>
                <failure>
                    <position line="simple.spec.c:110:" />
                    <error message="|> `[1, 2, 3, 4, 1]` expected but got `[7, 7, 7, 7, 7]" />
                </failure>
            <it/>
            <it name="succeeds `nassert_that_int_array`", status="passing" />
            <it name="fails `nassert_that_int_array`", status="failing">
                <failure>
                    <position line="simple.spec.c:118:" />
                    <error message="|> `[7, 7, 7, 7, 7]` expected but got `[7, 7, 7, 7, 7]" />
                </failure>
            <it/>
        </describe>
    </module>
    <module name="another_third", failures="18", skipped="1", tests="42", timestamp="2020-04-18 00:45:37">
        <describe name="Generic type assertions">
            <context name="when using generic asserts">
                <it name="succeeds generic int assertion", status="passing" />
                <it name="fails generic int assertion", status="failing">
                    <failure>
                        <position line="simple.spec.c:130:" />
                        <error message="|> `3` expected but got `2" />
                    </failure>
                <it/>
                <it name="succeeds generic int nassertion", status="passing" />
                <it name="fails generic int nassertion", status="failing">
                    <failure>
                        <position line="simple.spec.c:137:" />
                        <error message="|> `4` expected but got `4" />
                    </failure>
                <it/>
                <it name="succeeds generic double assertion", status="failing">
                    <failure>
                        <position line="simple.spec.c:141:" />
                        <error message="|> `3.2` expected but got `3.2" />
                    </failure>
                <it/>
                <it name="fails generic double assertion", status="passing" />
                <it name="succeeds generic double nassertion", status="failing">
                    <failure>
                        <position line="simple.spec.c:148:" />
                        <error message="|> `7.7` expected but got `6.6" />
                    </failure>
                <it/>
                <it name="fails generic double nassertion", status="passing" />
                <it name="fails generic int with double assertion", status="passing" />
                <it name="fails generic double with int assertion", status="passing" />
                <it name="succeeds generic int with double nassertion", status="failing">
                    <failure>
                        <position line="simple.spec.c:162:" />
                        <error message="|> `2.2` expected but got `2" />
                    </failure>
                <it/>
                <it name="succeeds generic double with int nassertion", status="failing">
                    <failure>
                        <position line="simple.spec.c:165:" />
                        <error message="|> `3` expected but got `3.3" />
                    </failure>
                <it/>
                <it name="succeeds generic string assertion", status="passing" />
                <it name="fails generic string assertion", status="failing">
                    <failure>
                        <position line="simple.spec.c:172:" />
                        <error message="|> `nottestme` expected but got `testme" />
                    </failure>
                <it/>
                <it name="succeeds generic string nassertion", status="passing" />
                <it name="fails generic string nassertion", status="failing">
                    <failure>
                        <position line="simple.spec.c:179:" />
                        <error message="|> `ok str` expected but got `ok str" />
                    </failure>
                <it/>
            </context>
            <context name="when we are finished">
                <it name="does nothing", status="passing" />
            </context>
        </describe>
    </module>
</modules>
